name: Starlight
favicon: null
layout_spectrum: 0.80398
typography_spectrum: 0.3242965927347541
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000228'
    - '#234d7f'
    - '#408cab'
    - '#85c5f5'
    - '#feffa7'
  brandStrength: 0.5
  lightness: 0.013377540512010455
  saturation: 0.49002967472188175
  rhythmicContrast: 0.15293103572912514
purpose: []
